-- Supabase bootstrap for my-blog
-- Run this in the Supabase SQL editor for a fresh project.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  content text not null,
  excerpt text,
  published boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.about_page (
  id integer primary key,
  content text not null default '',
  content_en text not null default '',
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  title text not null,
  title_en text not null default '',
  slug text not null unique,
  summary text,
  summary_en text,
  content text not null,
  content_en text not null default '',
  category text,
  tags text[] not null default '{}',
  published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.mcp_page (
  id integer primary key,
  content text not null default '',
  content_en text not null default '',
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists set_posts_updated_at on public.posts;
create trigger set_posts_updated_at
before update on public.posts
for each row
execute function public.set_updated_at();

drop trigger if exists set_about_page_updated_at on public.about_page;
create trigger set_about_page_updated_at
before update on public.about_page
for each row
execute function public.set_updated_at();

drop trigger if exists set_skills_updated_at on public.skills;
create trigger set_skills_updated_at
before update on public.skills
for each row
execute function public.set_updated_at();

drop trigger if exists set_mcp_page_updated_at on public.mcp_page;
create trigger set_mcp_page_updated_at
before update on public.mcp_page
for each row
execute function public.set_updated_at();

alter table public.posts enable row level security;
alter table public.about_page enable row level security;
alter table public.skills enable row level security;
alter table public.mcp_page enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.posts to anon, authenticated;
grant select, insert, update, delete on table public.about_page to anon, authenticated;
grant select, insert, update, delete on table public.skills to anon, authenticated;
grant select, insert, update, delete on table public.mcp_page to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists posts_public_read_published on public.posts;
create policy posts_public_read_published
on public.posts
for select
to anon
using (published = true);

drop policy if exists posts_authenticated_read_all on public.posts;
create policy posts_authenticated_read_all
on public.posts
for select
to authenticated
using (true);

drop policy if exists posts_authenticated_insert on public.posts;
create policy posts_authenticated_insert
on public.posts
for insert
to authenticated
with check (true);

drop policy if exists posts_authenticated_update on public.posts;
create policy posts_authenticated_update
on public.posts
for update
to authenticated
using (true)
with check (true);

drop policy if exists posts_authenticated_delete on public.posts;
create policy posts_authenticated_delete
on public.posts
for delete
to authenticated
using (true);

drop policy if exists about_page_read on public.about_page;
create policy about_page_read
on public.about_page
for select
to anon, authenticated
using (true);

drop policy if exists about_page_insert on public.about_page;
create policy about_page_insert
on public.about_page
for insert
to authenticated
with check (true);

drop policy if exists about_page_update on public.about_page;
create policy about_page_update
on public.about_page
for update
to authenticated
using (true)
with check (true);

drop policy if exists skills_public_read_published on public.skills;
create policy skills_public_read_published
on public.skills
for select
to anon
using (published = true);

drop policy if exists skills_authenticated_read_all on public.skills;
create policy skills_authenticated_read_all
on public.skills
for select
to authenticated
using (true);

drop policy if exists skills_authenticated_insert on public.skills;
create policy skills_authenticated_insert
on public.skills
for insert
to authenticated
with check (true);

drop policy if exists skills_authenticated_update on public.skills;
create policy skills_authenticated_update
on public.skills
for update
to authenticated
using (true)
with check (true);

drop policy if exists skills_authenticated_delete on public.skills;
create policy skills_authenticated_delete
on public.skills
for delete
to authenticated
using (true);

drop policy if exists mcp_page_read on public.mcp_page;
create policy mcp_page_read
on public.mcp_page
for select
to anon, authenticated
using (true);

drop policy if exists mcp_page_insert on public.mcp_page;
create policy mcp_page_insert
on public.mcp_page
for insert
to authenticated
with check (true);

drop policy if exists mcp_page_update on public.mcp_page;
create policy mcp_page_update
on public.mcp_page
for update
to authenticated
using (true)
with check (true);

insert into public.about_page (id, content, content_en)
values (1, '', '')
on conflict (id) do nothing;

insert into public.mcp_page (id, content, content_en)
values (1, '', '')
on conflict (id) do nothing;

insert into public.skills (
  title,
  title_en,
  slug,
  summary,
  summary_en,
  content,
  content_en,
  category,
  tags,
  published,
  sort_order
)
values (
  'Next.js + Supabase 博客脚手架',
  'Next.js + Supabase Blog Blueprint',
  'next-supabase-blog-blueprint',
  '一套通用的 Next.js + Supabase 个人知识系统蓝图，用于搭建公开博客、Skills 知识库、后台管理、认证、Spec 与 Harness 验收闭环。',
  'A reusable Next.js + Supabase blueprint for a personal knowledge system with public blog pages, a Skills library, admin CRUD, auth, specs, and harness checks.',
  '## 目标

搭建一个个人博客与技能库一体化系统，但文章和 Skills 必须是两个独立内容体系。文章用于时间线写作，Skills 用于沉淀可复用的方法论、脚手架和工程蓝图。

## 架构

- Next.js App Router 负责页面、Route Handler 和 Proxy。
- Supabase Postgres 负责内容数据，Supabase Auth 负责后台登录。
- RLS 控制公开读和后台管理权限。
- 内容由后台人工维护；自动生成文章不属于当前范围。

## 内容体系

- posts：文章体系，面向时间线发布。
- skills：技能体系，面向可复用能力、脚手架和架构蓝图。
- about_page / mcp_page：单例页面内容。

## 标准脚手架

新项目应优先补齐：

1. ai-rules.project.json：声明项目继承 frontend 规则。
2. docs/architecture/app-map.md：记录技术栈、路由、数据表和运行入口。
3. docs/architecture/exceptions.md：登记 Next.js、Tailwind、npm 等与统一前端默认栈的差异。
4. docs/specs/blog/*：记录博客与 Skills 知识库的流程、契约和验收。
5. tests/harness/*：提供 knowledge、contracts、journeys 的验证入口。

## 数据库设计

skills 表是第一等业务表，至少包含 title、slug、summary、content、category、tags、published、sort_order 和时间字段。中英文内容通过 title_en、summary_en、content_en 承载。

## 使用方式

当需要搭建同类项目时，先复制架构骨架，再按项目实际删减场景包。不要把 Skills 当成普通文章，也不要把架构知识只写在 prompt 里。',
  '## Goal

Build an integrated personal blog and skill library where posts and skills are separate content systems. Posts are chronological writing. Skills are reusable methods, scaffolds, and architecture blueprints.

## Architecture

- Next.js App Router owns pages, route handlers, and Proxy.
- Supabase Postgres stores content, and Supabase Auth protects admin access.
- RLS separates public reads from authenticated content management.
- Content is maintained through the admin UI; automated article generation is out of scope.

## Content Systems

- posts: chronological blog posts.
- skills: reusable capabilities, scaffolds, and architecture blueprints.
- about_page / mcp_page: singleton content pages.

## Standard Scaffold

A similar project should start with:

1. ai-rules.project.json for frontend rule inheritance.
2. docs/architecture/app-map.md for stack, routes, tables, and runtime entrypoints.
3. docs/architecture/exceptions.md for Next.js, Tailwind, npm, and other standard-stack exceptions.
4. docs/specs/blog/* for journeys, contracts, and acceptance.
5. tests/harness/* for knowledge, contracts, and journeys validation.

## Database Design

The skills table is a first-class business table with title, slug, summary, content, category, tags, published, sort_order, and timestamps. English content is stored in title_en, summary_en, and content_en.

## Usage

When building a similar project, copy the architecture scaffold first and then trim scenario packs by actual needs. Do not treat Skills as ordinary posts, and do not keep architecture knowledge only in prompts.',
  'blueprint',
  array['nextjs', 'supabase', 'architecture', 'harness'],
  true,
  10
)
on conflict (slug) do nothing;
